#!/bin/bash

sudo sed -i 's/kr.archive.ubuntu.com/ftp.daum.net/g' /etc/apt/sources.list
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get autoremove
sudo apt-get -y install python-setuptools git

sudo easy_install pip
sudo pip install virtualenvwrapper

WORKON_HOME=~/.virtualenvs
BASH_PROFILE=~/.profile

echo export WORKON_HOME=$WORKON_HOME >> $BASH_PROFILE
echo export PIP_VIRTUALENV_BASE=$WORKON_HOME >> $BASH_PROFILE
echo export PIP_RESPECT_VIRTUALENV=true >> $BASH_PROFILE
echo source `which virtualenvwrapper.sh` >> $BASH_PROFILE

mkdir $WORKON_HOME
source $BASH_PROFILE
