#!/bin/bash

sed -i 's/kr.archive.ubuntu.com/ftp.daum.net/g' /etc/apt/sources.list
apt-get update
apt-get -y upgrade
apt-get autoremove
apt-get -y install python-setuptools
easy_install pip
pip install virtualenvwrapper
