#!/bin/bash

sudo sed -i 's/kr.archive.ubuntu.com/ftp.daum.net/g' /etc/apt/sources.list
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get autoremove
sudo apt-get -y install python-setuptools
sudo easy_install pip
sudo pip install virtualenvwrapper

echo export WORKON_HOME=~/.virtualenvs >> ~/.profile
echo export PIP_VIRTUALENV_BASE=$WORKON_HOME >> ~/.profile
echo export PIP_RESPECT_VIRTUALENV=true >> ~/.profile
echo source `which /usr/local/bin/virtualenvwrapper.sh` >> ~/.profile

mkdir ~/.virtualenvs
source ~/.profile
